# ================================================================
#  FolderBoy.ps1  |  Media Library Manager
#  https://github.com/sfaith/FolderBoy
#
#  A PowerShell toolkit for managing Sonarr, Radarr, and Lidarr
#  media libraries. Includes six tools:
#
#    1. FolderBoy Cleaner      -- removes folders that contain no
#                                 recognized media files (filesystem
#                                 only, no *arr API calls required).
#
#    2. Sonarr Folder Renamer  -- renames series folders to match the
#                                 TRaSH Guides recommended format with
#                                 {imdb-} ID tags, and updates Sonarr
#                                 paths via API.
#
#    3. Radarr Folder Renamer  -- renames movie folders to match the
#                                 TRaSH Guides recommended format and
#                                 updates Radarr paths via API.
#
#    4. Lidarr Folder Renamer  -- renames artist folders to match the
#                                 Lidarr recommended format and updates
#                                 Lidarr paths via API.
#
#    5. Orphan Scanner         -- compares what is on disk against
#                                 what each *arr app manages. Reports
#                                 unrecognized folders by confidence
#                                 level, with optional interactive
#                                 delete.
#
#    6. Full Run               -- runs all three Folder Renamers then
#                                 Orphan Scanner in sequence
#                                 (recommended workflow).
#
#  REQUIREMENTS:
#    - PowerShell 5.1 or later (built into Windows 10/11/Server)
#    - FolderBoy.config.ps1 in the same folder as this script
#    - Network access to each *arr application's API
#
#  QUICK START:
#    1. Copy FolderBoy.config.example.ps1 to FolderBoy.config.ps1
#    2. Edit FolderBoy.config.ps1 with your settings
#    3. Run: .\FolderBoy.ps1  (or double-click FolderBoy.bat)
#
#  USER CONFIGURATION:
#    All settings (API keys, paths, presets) live in
#    FolderBoy.config.ps1. Do not edit this file for configuration.
# ================================================================

# ================================================================
#  LOAD CONFIG
# ================================================================
$ConfigFile = Join-Path $PSScriptRoot 'FolderBoy.config.ps1'

if (-not (Test-Path -LiteralPath $ConfigFile)) {
    Write-Host ''
    Write-Host '  ============================================================' -ForegroundColor Red
    Write-Host '   FolderBoy -- Configuration file not found' -ForegroundColor Red
    Write-Host '  ============================================================' -ForegroundColor Red
    Write-Host ''
    Write-Host '  FolderBoy.config.ps1 was not found in the script folder.' -ForegroundColor Yellow
    Write-Host ''
    Write-Host '  To set up:' -ForegroundColor White
    Write-Host '    1. Copy FolderBoy.config.example.ps1 to FolderBoy.config.ps1' -ForegroundColor White
    Write-Host '    2. Open FolderBoy.config.ps1 and fill in your settings' -ForegroundColor White
    Write-Host '    3. Run FolderBoy again' -ForegroundColor White
    Write-Host ''
    Write-Host ("  Expected config path: {0}" -f $ConfigFile) -ForegroundColor DarkGray
    Write-Host ''
    exit
}

try {
    . $ConfigFile
} catch {
    Write-Host ''
    Write-Host '  ============================================================' -ForegroundColor Red
    Write-Host '   FolderBoy -- Error loading configuration' -ForegroundColor Red
    Write-Host '  ============================================================' -ForegroundColor Red
    Write-Host ''
    Write-Host '  FolderBoy.config.ps1 was found but could not be loaded.' -ForegroundColor Yellow
    Write-Host '  Check the file for syntax errors.' -ForegroundColor Yellow
    Write-Host ''
    Write-Host ("  Error: {0}" -f $_) -ForegroundColor Red
    Write-Host ''
    exit
}

# Validate that the required config variables were defined
$configErrors = @()
if ($null -eq $FolderBoyPresets) { $configErrors += '$FolderBoyPresets is not defined' }
if ($null -eq $RadarrConfig)     { $configErrors += '$RadarrConfig is not defined' }
if ($null -eq $SonarrConfig)     { $configErrors += '$SonarrConfig is not defined' }
if ($null -eq $LidarrConfig)     { $configErrors += '$LidarrConfig is not defined' }
if ($null -eq $PathPad)          { $Script:PathPad = 80 }

if ($configErrors.Count) {
    Write-Host ''
    Write-Host '  ============================================================' -ForegroundColor Red
    Write-Host '   FolderBoy -- Incomplete configuration' -ForegroundColor Red
    Write-Host '  ============================================================' -ForegroundColor Red
    Write-Host ''
    Write-Host '  The following required variables are missing from FolderBoy.config.ps1:' -ForegroundColor Yellow
    foreach ($e in $configErrors) { Write-Host ("    - {0}" -f $e) -ForegroundColor Red }
    Write-Host ''
    Write-Host '  Compare your config file against FolderBoy.config.example.ps1.' -ForegroundColor White
    Write-Host ''
    exit
}

# ================================================================
#  SHARED HELPERS
# ================================================================
$Script:LogFile = $null

function Start-Log ([string]$Prefix) {
    $Script:LogFile = Join-Path $PSScriptRoot ("{0}_{1}.log" -f $Prefix, (Get-Date -Format 'yyyyMMdd_HHmmss'))
}

function Write-Log {
    param([string]$Message, [string]$Color = 'White')
    Write-Host $Message -ForegroundColor $Color
    if ($Script:LogFile) {
        $Message | Out-File $Script:LogFile -Append -Encoding utf8
    }
}

function Write-SectionHeader ([string]$Title) {
    Write-Log ''
    Write-Log ('  ' + ('=' * 66)) 'Cyan'
    Write-Log ("  $Title") 'Cyan'
    Write-Log ('  ' + ('=' * 66)) 'Cyan'
}

function Write-Tip ([string]$Message) {
    Write-Log ("  [TIP] {0}" -f $Message) 'DarkCyan'
}

function Get-FolderSizeBytes ([string]$Path) {
    $bytes = (Get-ChildItem -LiteralPath $Path -Recurse -ErrorAction SilentlyContinue |
              Where-Object { -not $_.PSIsContainer } |
              Measure-Object -Property Length -Sum).Sum
    if ($bytes) { return [long]$bytes } else { return [long]0 }
}

function Format-Bytes ([long]$Bytes) {
    if ($Bytes -ge 1GB) { return ('{0:N2} GB' -f ($Bytes / 1GB)) }
    if ($Bytes -ge 1MB) { return ('{0:N1} MB' -f ($Bytes / 1MB)) }
    return ('{0} B' -f $Bytes)
}

function Get-FolderSize ([string]$Path) {
    $b = Get-FolderSizeBytes $Path
    return @{ Bytes = $b; Display = Format-Bytes $b }
}

function Normalize ([string]$s) {
    return ($s.ToLower() -replace '[^a-z0-9]', '')
}

function Normalize-Path ([string]$p) {
    return $p.ToLower().TrimEnd('\').TrimEnd('/') -replace '/', '\'
}

function Invoke-ArrApi {
    param([string]$BaseUrl, [string]$ApiKey, [string]$Endpoint, [string]$ApiVersion = 'v3')
    $uri = "$($BaseUrl.TrimEnd('/'))/api/$ApiVersion/$Endpoint"
    try {
        return Invoke-RestMethod -Uri $uri `
            -Headers @{ 'X-Api-Key' = $ApiKey } `
            -Method Get -ErrorAction Stop
    }
    catch {
        Write-Log ("  [ERROR] API call failed: {0}" -f $uri) 'Red'
        Write-Log ("          {0}" -f $_) 'Red'
        return $null
    }
}

function Confirm-LiveAction ([string]$Warning) {
    Write-Log ''
    Write-Log ("  WARNING: {0}" -f $Warning) 'Red'
    Write-Log '  This action cannot be undone. A log will be saved next to this script.' 'Yellow'
    Write-Log ''
    $confirm = Read-Host '  Type YES to proceed, or anything else to abort'
    if ($confirm -ne 'YES') {
        Write-Log '  Aborted. No changes were made.' 'Yellow'
        return $false
    }
    Write-Log ''
    return $true
}

# ================================================================
#  TOOL 1: FOLDERBOY CLEANER
# ================================================================
function Invoke-FolderBoyCleaner {
    param([bool]$LiveDelete = $false)

    Start-Log 'FolderBoy'
    $modeLabel = if ($LiveDelete) { 'Live Delete' } else { 'Dry Run' }

    Write-Log ''
    Write-Log '  ============================================================' 'Cyan'
    Write-Log ("   FolderBoy Cleaner -- {0}" -f $modeLabel) 'Cyan'
    Write-Log ('   {0}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')) 'Cyan'
    Write-Log '  ============================================================' 'Cyan'

    if (-not $LiveDelete) {
        Write-Log ''
        Write-Log '  DRY RUN MODE: No files or folders will be deleted.' 'Cyan'
        Write-Log '  This run shows you exactly what WOULD be removed.' 'Cyan'
        Write-Log '  Review the output, then re-run and choose Live Delete to apply.' 'Cyan'
    }

    Write-Log ''
    Write-Log '  Select media type:' 'Cyan'
    Write-Log ''
    foreach ($key in $FolderBoyPresets.Keys) {
        Write-Log ("    ({0}) {1}" -f $key, $FolderBoyPresets[$key].Label)
    }
    Write-Log ''
    do { $choice = Read-Host '  Choice' } until ($FolderBoyPresets.Contains($choice))
    $preset = $FolderBoyPresets[$choice]

    if ($choice -eq ($FolderBoyPresets.Keys | Select-Object -Last 1)) {
        # Custom preset
        $customInput = Read-Host '  Enter extensions comma-separated (e.g. mp3,flac,wav)'
        $mediaExts = $customInput -split ',' | ForEach-Object {
            $e = $_.Trim().ToLower()
            if ($e -notmatch '^\.' ) { ".$e" } else { $e }
        }
        $label     = 'Custom'
        $scanPaths = @(Read-Host '  Enter root path to scan')
    } else {
        $mediaExts = $preset.Exts
        $label     = $preset.Label
        $scanPaths = $preset.Paths

        if ($preset.Paths.Count -gt 1) {
            Write-Log ''
            Write-Log '  Select path to scan:' 'Cyan'
            Write-Log ''
            for ($i = 0; $i -lt $preset.Paths.Count; $i++) {
                Write-Log ("    ({0}) {1}" -f ($i + 1), $preset.Paths[$i])
            }
            Write-Log ("    ({0}) All paths" -f ($preset.Paths.Count + 1))
            Write-Log ''
            do {
                $pathChoice = Read-Host '  Choice'
                $pathIdx = 0
                $validPath = [int]::TryParse($pathChoice, [ref]$pathIdx) -and
                             $pathIdx -ge 1 -and $pathIdx -le ($preset.Paths.Count + 1)
            } until ($validPath)
            if ($pathIdx -le $preset.Paths.Count) {
                $scanPaths = @($preset.Paths[$pathIdx - 1])
            }
        }
    }

    Write-Log ''
    Write-Log ("  Scanning for  : {0}" -f $label) 'Yellow'
    Write-Log ("  Extensions    : {0}" -f ($mediaExts -join ', ')) 'Yellow'
    foreach ($p in $scanPaths) { Write-Log ("  Path          : {0}" -f $p) 'Yellow' }

    if ($LiveDelete) {
        if (-not (Confirm-LiveAction 'This will permanently delete folders containing no media files.')) { return }
    } else {
        Write-Log ''
    }

    $toDelete   = [System.Collections.Generic.List[string]]::new()
    $totalBytes = [long]0
    $extTally   = @{}
    $deleted    = [System.Collections.Generic.List[string]]::new()
    $failed     = [System.Collections.Generic.List[string]]::new()

    Write-Log ('  ' + ('-' * 66))

    foreach ($root in $scanPaths) {
        if (-not (Test-Path -LiteralPath $root)) {
            Write-Log ("  [WARN] Path not found: {0}" -f $root) 'Yellow'
            continue
        }

        $allFolders = Get-ChildItem -Path $root -Recurse -ErrorAction SilentlyContinue |
                      Where-Object { $_.PSIsContainer } |
                      Sort-Object { $_.FullName.Length } -Descending

        Write-Log ("  Scanning {0}  ({1} subfolders)" -f $root, $allFolders.Count) 'White'

        foreach ($folder in $allFolders) {
            if ($LiveDelete -and -not (Test-Path -LiteralPath $folder.FullName)) { continue }

            $hasMedia = Get-ChildItem -LiteralPath $folder.FullName -Recurse -ErrorAction SilentlyContinue |
                        Where-Object { -not $_.PSIsContainer -and $mediaExts -contains $_.Extension.ToLower() } |
                        Select-Object -First 1

            if (-not $hasMedia) {
                $files     = Get-ChildItem -LiteralPath $folder.FullName -Recurse -ErrorAction SilentlyContinue |
                             Where-Object { -not $_.PSIsContainer }
                $sizeBytes = if (($s = ($files | Measure-Object -Property Length -Sum).Sum)) { [long]$s } else { [long]0 }
                $sizeMB    = [math]::Round($sizeBytes / 1MB, 1)

                foreach ($file in $files) {
                    $ext = if ($file.Extension) { $file.Extension.ToLower() } else { '(no ext)' }
                    if (-not $extTally[$ext]) { $extTally[$ext] = @{ Count = 0; Bytes = [long]0 } }
                    $extTally[$ext].Count++
                    $extTally[$ext].Bytes += $file.Length
                }

                if ($LiveDelete) {
                    try {
                        Remove-Item -LiteralPath $folder.FullName -Recurse -Force -ErrorAction Stop
                        Write-Log ("  [DELETED] {0}  ({1} MB)" -f $folder.FullName.PadRight($PathPad), $sizeMB) 'Green'
                        $deleted.Add($folder.FullName)
                        $totalBytes += $sizeBytes
                    } catch {
                        Write-Log ("  [FAILED]  {0}" -f $folder.FullName) 'Red'
                        Write-Log ("            {0}" -f $_) 'Red'
                        $failed.Add($folder.FullName)
                    }
                } else {
                    Write-Log ("  [WOULD DELETE] {0}  ({1} MB)" -f $folder.FullName.PadRight($PathPad), $sizeMB) 'Yellow'
                    $toDelete.Add($folder.FullName)
                    $totalBytes += $sizeBytes
                }
            }
        }
    }

    $totalGB = [math]::Round($totalBytes / 1GB, 2)
    $totalMB = [math]::Round($totalBytes / 1MB, 1)

    Write-Log ('  ' + ('-' * 66))
    Write-Log ''

    if ($LiveDelete) {
        Write-Log ("  Deleted   : {0}  folders" -f $deleted.Count) 'Green'
        Write-Log ("  Failed    : {0}  folders" -f $failed.Count) $(if ($failed.Count) { 'Red' } else { 'Green' })
        Write-Log ("  Reclaimed : {0} GB  ({1} MB)" -f $totalGB, $totalMB) 'Green'
    } else {
        Write-Log ("  Would delete  : {0}  folders" -f $toDelete.Count) 'Yellow'
        Write-Log ("  Reclaimable   : {0} GB  ({1} MB)" -f $totalGB, $totalMB) 'Yellow'
        Write-Log ''
        Write-Log '  Re-run and choose Live Delete to apply these changes.' 'Cyan'
    }

    if ($extTally.Count) {
        Write-Log ''
        Write-Log '  Non-media file types found in flagged folders:' 'DarkGray'
        Write-Log ('  {0,-22} {1,8}   {2,10}' -f 'Extension', 'Files', 'Size') 'DarkGray'
        $extTally.GetEnumerator() | Sort-Object { $_.Value.Bytes } -Descending | ForEach-Object {
            $extMB = [math]::Round($_.Value.Bytes / 1MB, 1)
            Write-Log ('  {0,-22} {1,8}   {2,7} MB' -f $_.Key, $_.Value.Count, $extMB) 'DarkGray'
        }
    }

    Write-Log ''
    Write-Log ("  Log saved to: {0}" -f $Script:LogFile) 'Cyan'

    return @{ Label = $label; Paths = $scanPaths }
}

# ================================================================
#  TOOL 2: SONARR FOLDER RENAMER
# ================================================================
function Invoke-SonarrGet ([string]$Endpoint) {
    $uri = "$($SonarrConfig.BaseUrl.TrimEnd('/'))/api/v3/$Endpoint"
    try {
        return Invoke-RestMethod -Uri $uri `
            -Headers @{ 'X-Api-Key' = $SonarrConfig.ApiKey } `
            -Method Get -ErrorAction Stop
    }
    catch {
        Write-Log ("  [ERROR] GET {0} -- {1}" -f $uri, $_) 'Red'
        return $null
    }
}

function Invoke-SonarrPut ([string]$Endpoint, [object]$Body) {
    $uri = "$($SonarrConfig.BaseUrl.TrimEnd('/'))/api/v3/$Endpoint"
    try {
        $json  = $Body | ConvertTo-Json -Depth 20 -Compress
        # Send as UTF-8 bytes -- required for series with non-ASCII
        # characters in alternate titles. Sending as a plain string
        # causes Sonarr to return 400 Bad Request for these series.
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($json)
        return Invoke-RestMethod -Uri $uri `
            -Headers @{ 'X-Api-Key' = $SonarrConfig.ApiKey; 'Content-Type' = 'application/json; charset=utf-8' } `
            -Method Put -Body $bytes -ErrorAction Stop
    }
    catch {
        Write-Log ("  [ERROR] PUT {0} -- {1}" -f $uri, $_) 'Red'
        return $null
    }
}

function Get-CleanTitle ([string]$Title) {
    # Mirrors Sonarr's title sanitization:
    # colons become space-dash, forward slash removed,
    # other illegal Windows filename characters removed.
    $clean = $Title -replace ':', ' -'
    $clean = $clean -replace '[\\/<>"\|\?\*]', ''
    $clean = $clean -replace '\s+', ' '
    return $clean.Trim()
}

function Test-TitleMatch ([string]$FolderName, [string]$SonarrTitle) {
    # Returns $true if the folder name (minus tag blocks) normalizes
    # to the same string as the Sonarr title, or matches the title
    # without its disambiguation year.
    # Prevents accidental renames of folders that were manually named
    # differently from what Sonarr would generate.
    $folderBase       = ($FolderName -replace '\{[^}]+\}', '' -replace '\s+', ' ').Trim()
    $normalize        = { param($s) ($s.ToLower() -replace '[^a-z0-9]', '') }
    $normFolder       = & $normalize $folderBase
    $normSonarr       = & $normalize (Get-CleanTitle $SonarrTitle)
    $sonarrNoYear     = (Get-CleanTitle $SonarrTitle) -replace '\s*\(\d{4}\)\s*$', ''
    $normSonarrNoYear = & $normalize $sonarrNoYear
    return ($normFolder -eq $normSonarr) -or ($normFolder -eq $normSonarrNoYear)
}

function Get-TargetFolderName ([string]$Title, [int]$Year, [string]$ImdbId) {
    # Builds: {Series TitleYear} {imdb-{ImdbId}}
    # e.g.   The Wire (2002) {imdb-tt0306414}
    # Does not append year if the clean title already ends with (YYYY).
    $clean = Get-CleanTitle $Title
    if ($Year -gt 0 -and $clean -notmatch '\(\d{4}\)\s*$') {
        return "{0} ({1}) {{imdb-{2}}}" -f $clean, $Year, $ImdbId
    } else {
        return "{0} {{imdb-{1}}}" -f $clean, $ImdbId
    }
}

function Invoke-SonarrRenamer {
    param([bool]$LiveRename = $false)

    Start-Log 'FolderBoy_SonarrRenamer'
    $modeLabel = if ($LiveRename) { 'Live Rename' } else { 'Dry Run' }

    Write-Log ''
    Write-Log '  ============================================================' 'Cyan'
    Write-Log ("   Sonarr Folder Renamer -- {0}" -f $modeLabel) 'Cyan'
    Write-Log ('   {0}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')) 'Cyan'
    Write-Log '  ============================================================' 'Cyan'

    if (-not $LiveRename) {
        Write-Log ''
        Write-Log '  DRY RUN MODE: No folders will be renamed. Sonarr will not be updated.' 'Cyan'
        Write-Log '  This run previews what WOULD be renamed.' 'Cyan'
        Write-Log '  Review the output, then re-run and choose Live Rename to apply.' 'Cyan'
    }

    Write-Log ''
    Write-Tip 'Sonarr Series Folder Format should be: {Series TitleYear} {imdb-{ImdbId}}'
    Write-Tip 'Set in Sonarr: Settings > Media Management > (show advanced) > Series Folder Format'
    Write-Tip 'Guide: https://trash-guides.info/Sonarr/Sonarr-recommended-naming-scheme/'
    Write-Log ''

    if ($LiveRename) {
        if (-not (Confirm-LiveAction 'This will rename series folders on disk and update Sonarr paths via API.')) { return }
    }

    Write-Log '  Fetching Sonarr library...' 'White'
    $allSeries = Invoke-SonarrGet 'series'
    if (-not $allSeries) {
        Write-Log '  Could not reach Sonarr API. Check BaseUrl and ApiKey in FolderBoy.config.ps1.' 'Red'
        return
    }
    Write-Log ("  Found {0} series in Sonarr." -f $allSeries.Count) 'White'
    Write-Log ''

    $counts = @{
        AlreadyTagged = 0; NoImdbId = 0; NoPath = 0
        PathMissing   = 0; Renamed  = 0; Failed = 0; Skipped = 0
    }
    $noImdbList = [System.Collections.Generic.List[string]]::new()
    $failedList = [System.Collections.Generic.List[string]]::new()

    Write-SectionHeader 'PROCESSING SERIES'
    Write-Log ''

    foreach ($series in $allSeries | Sort-Object title) {
        $currentPath = $series.path.TrimEnd('\').TrimEnd('/')
        $title       = $series.title
        $year        = $series.year
        $imdbId      = $series.imdbId
        $seriesId    = $series.id

        if (-not $currentPath) { $counts.NoPath++; continue }

        $folderName = Split-Path $currentPath -Leaf
        $parentDir  = Split-Path $currentPath -Parent

        if ($folderName -match '\{imdb-tt\d+\}') { $counts.AlreadyTagged++; continue }

        if (-not $imdbId) {
            Write-Log ("  [NO IMDB ID] {0}" -f $title) 'Yellow'
            $noImdbList.Add($title)
            $counts.NoImdbId++
            continue
        }

        if (-not (Test-Path -LiteralPath $currentPath)) {
            Write-Log ("  [MISSING]    {0} -- path not found: {1}" -f $title, $currentPath) 'Yellow'
            $counts.PathMissing++
            continue
        }

        if (-not (Test-TitleMatch $folderName $title)) {
            Write-Log ("  [MISMATCH]   {0}" -f $title) 'Yellow'
            Write-Log ("      Folder : {0}" -f $folderName) 'Yellow'
            Write-Log ("      Sonarr : {0}" -f (Get-CleanTitle $title)) 'Yellow'
            Write-Log ("      Skipped -- rename folder manually to match Sonarr title, then re-run.") 'Yellow'
            $counts.Skipped++
            continue
        }

        $newFolderName = Get-TargetFolderName $title $year $imdbId
        $newPath       = Join-Path $parentDir $newFolderName

        if ($folderName -eq $newFolderName) { $counts.AlreadyTagged++; continue }

        if (-not $LiveRename) {
            Write-Log ("  [WOULD RENAME]") 'White'
            Write-Log ("      From : {0}" -f $currentPath) 'White'
            Write-Log ("      To   : {0}" -f $newPath) 'Cyan'
            $counts.Renamed++
        } else {
            if ((Test-Path -LiteralPath $newPath) -and ($newPath -ne $currentPath)) {
                Write-Log ("  [CONFLICT]   {0} -- target folder already exists." -f $title) 'Red'
                $failedList.Add(("{0} -- target folder already exists" -f $title))
                $counts.Failed++
                continue
            }
            try {
                Rename-Item -LiteralPath $currentPath -NewName $newFolderName -ErrorAction Stop
                $series.path = $newPath
                $result = Invoke-SonarrPut "series/$seriesId" $series
                if ($result) {
                    Write-Log ("  [RENAMED]") 'Green'
                    Write-Log ("      From : {0}" -f $currentPath) 'Green'
                    Write-Log ("      To   : {0}" -f $newPath) 'Green'
                    $counts.Renamed++
                } else {
                    Write-Log ("  [API FAIL]   {0} -- folder renamed but Sonarr update failed. Rolling back." -f $title) 'Red'
                    try {
                        Rename-Item -LiteralPath $newPath -NewName $folderName -ErrorAction Stop
                        Write-Log ("               Rollback successful.") 'Yellow'
                    } catch {
                        Write-Log ("               Rollback FAILED. Folder is now at: {0}" -f $newPath) 'Red'
                        Write-Log ("               Manually update the path in Sonarr for this series.") 'Red'
                    }
                    $failedList.Add(("{0} -- Sonarr API update failed" -f $title))
                    $counts.Failed++
                }
            } catch {
                Write-Log ("  [ERROR]      {0} -- {1}" -f $title, $_) 'Red'
                $failedList.Add(("{0} -- {1}" -f $title, $_))
                $counts.Failed++
            }
        }
    }

    Write-Log ''
    Write-SectionHeader 'SUMMARY'
    Write-Log ''

    if ($LiveRename) {
        Write-Log ("  Renamed        : {0}  series" -f $counts.Renamed) 'Green'
        Write-Log ("  Failed         : {0}  series" -f $counts.Failed) $(if ($counts.Failed) { 'Red' } else { 'Green' })
    } else {
        Write-Log ("  Would rename   : {0}  series" -f $counts.Renamed) 'Cyan'
    }
    Write-Log ("  Already tagged : {0}  series" -f $counts.AlreadyTagged) 'White'
    Write-Log ("  No IMDb ID     : {0}  series (cannot tag -- add ID in Sonarr)" -f $counts.NoImdbId) 'Yellow'
    Write-Log ("  Title mismatch : {0}  series (skipped -- rename folder manually)" -f $counts.Skipped) 'Yellow'
    Write-Log ("  Path missing   : {0}  series (Sonarr path not found on disk)" -f $counts.PathMissing) 'Yellow'

    if ($noImdbList.Count) {
        Write-Log ''
        Write-Log '  Series with no IMDb ID in Sonarr:' 'Yellow'
        foreach ($s in $noImdbList | Sort-Object) { Write-Log ("    - {0}" -f $s) 'Yellow' }
        Write-Tip 'To add an IMDb ID: open the series in Sonarr > Edit > External IDs'
    }
    if ($failedList.Count) {
        Write-Log ''
        Write-Log '  Failed renames (require manual attention):' 'Red'
        foreach ($f in $failedList) { Write-Log ("    - {0}" -f $f) 'Red' }
    }

    Write-Log ''
    if (-not $LiveRename) {
        Write-Log '  Re-run and choose Live Rename to apply these changes.' 'Cyan'
    } else {
        Write-Log '  Done.' 'Green'
    }
    Write-Log ("  Log saved to: {0}" -f $Script:LogFile) 'Cyan'
}


# ================================================================
#  TOOL 3: RADARR FOLDER RENAMER
# ================================================================
function Invoke-RadarrGet ([string]$Endpoint) {
    $uri = "$($RadarrConfig.BaseUrl.TrimEnd('/'))/api/v3/$Endpoint"
    try {
        return Invoke-RestMethod -Uri $uri `
            -Headers @{ 'X-Api-Key' = $RadarrConfig.ApiKey } `
            -Method Get -ErrorAction Stop
    }
    catch {
        Write-Log ("  [ERROR] GET {0} -- {1}" -f $uri, $_) 'Red'
        return $null
    }
}

function Invoke-RadarrPut ([string]$Endpoint, [object]$Body) {
    $uri = "$($RadarrConfig.BaseUrl.TrimEnd('/'))/api/v3/$Endpoint"
    try {
        $json  = $Body | ConvertTo-Json -Depth 20 -Compress
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($json)
        return Invoke-RestMethod -Uri $uri `
            -Headers @{ 'X-Api-Key' = $RadarrConfig.ApiKey; 'Content-Type' = 'application/json; charset=utf-8' } `
            -Method Put -Body $bytes -ErrorAction Stop
    }
    catch {
        Write-Log ("  [ERROR] PUT {0} -- {1}" -f $uri, $_) 'Red'
        return $null
    }
}

function Get-RadarrCleanTitle ([string]$Title) {
    # Mirrors Radarr's {Movie CleanTitle} token behavior:
    # illegal Windows filename characters are removed entirely.
    # Radarr folder names use CleanTitle which drops colons, slashes etc.
    # e.g. "3:10 to Yuma" becomes "310 to Yuma", not "3 -10 to Yuma".
    $clean = $Title -replace '[:\/<>"\|\?\*]', ''
    $clean = $clean -replace '\s+', ' '
    return $clean.Trim()
}

function Get-RadarrTargetFolderName ([string]$Title, [int]$Year, [string]$ImdbId, [bool]$UsePlex) {
    # Minimum: {Movie CleanTitle} ({Release Year})
    # Plex:    {Movie CleanTitle} ({Release Year}) {imdb-{ImdbId}}
    $clean = Get-RadarrCleanTitle $Title
    if ($UsePlex -and $ImdbId) {
        return "{0} ({1}) {{imdb-{2}}}" -f $clean, $Year, $ImdbId
    } else {
        return "{0} ({1})" -f $clean, $Year
    }
}

function Invoke-RadarrFolderRenamer {
    param([bool]$LiveRename = $false)

    Start-Log 'FolderBoy_RadarrRenamer'
    $modeLabel = if ($LiveRename) { 'Live Rename' } else { 'Dry Run' }

    Write-Log ''
    Write-Log '  ============================================================' 'Cyan'
    Write-Log ("   Radarr Folder Renamer -- {0}" -f $modeLabel) 'Cyan'
    Write-Log ('   {0}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')) 'Cyan'
    Write-Log '  ============================================================' 'Cyan'

    if (-not $LiveRename) {
        Write-Log ''
        Write-Log '  DRY RUN MODE: No folders will be renamed. Radarr will not be updated.' 'Cyan'
        Write-Log '  This run previews what WOULD be renamed.' 'Cyan'
        Write-Log '  Review the output, then re-run and choose Live Rename to apply.' 'Cyan'
    }

    Write-Log ''
    Write-Tip 'Radarr Movie Folder Format (minimum): {Movie CleanTitle} ({Release Year})'
    Write-Tip 'Radarr Movie Folder Format (Plex):    {Movie CleanTitle} ({Release Year}) {imdb-{ImdbId}}'
    Write-Tip 'Set in Radarr: Settings > Media Management > (show advanced) > Movie Folder Format'
    Write-Tip 'Guide: https://trash-guides.info/Radarr/Radarr-recommended-naming-scheme/'
    Write-Log ''

    # Ask user which format to target
    Write-Log '  Select target folder format:' 'Cyan'
    Write-Log ''
    Write-Log '    (1) Minimum  -- {Movie CleanTitle} ({Release Year})'
    Write-Log '                    Example: The Dark Knight (2008)'
    Write-Log '    (2) Plex     -- {Movie CleanTitle} ({Release Year}) {imdb-{ImdbId}}'
    Write-Log '                    Example: The Dark Knight (2008) {imdb-tt0468569}'
    Write-Log ''
    do { $formatChoice = Read-Host '  Choice' } until ($formatChoice -in '1','2')
    $usePlex = ($formatChoice -eq '2')

    if ($usePlex) {
        Write-Log '  Format: Plex (with IMDb ID tag)' 'Yellow'
        Write-Log '  Note: Movies with no IMDb ID in Radarr will use minimum format.' 'DarkGray'
    } else {
        Write-Log '  Format: Minimum ({Movie CleanTitle} ({Release Year}))' 'Yellow'
    }
    Write-Log ''

    if ($LiveRename) {
        if (-not (Confirm-LiveAction 'This will rename movie folders on disk and update Radarr paths via API.')) { return }
    }

    Write-Log '  Fetching Radarr library...' 'White'
    $allMovies = Invoke-RadarrGet 'movie'
    if (-not $allMovies) {
        Write-Log '  Could not reach Radarr API. Check BaseUrl and ApiKey in FolderBoy.config.ps1.' 'Red'
        return
    }
    Write-Log ("  Found {0} movies in Radarr." -f $allMovies.Count) 'White'
    Write-Log ''

    $counts = @{
        AlreadyCorrect = 0; NoPath = 0; PathMissing = 0
        Renamed        = 0; Failed = 0; NoYear = 0
    }
    $failedList = [System.Collections.Generic.List[string]]::new()
    $noYearList = [System.Collections.Generic.List[string]]::new()

    Write-SectionHeader 'PROCESSING MOVIES'
    Write-Log ''

    foreach ($movie in $allMovies | Sort-Object title) {
        $currentPath = if ($movie.path) { $movie.path.TrimEnd('\').TrimEnd('/') } else { $null }
        $title       = $movie.title
        $year        = $movie.year
        $imdbId      = $movie.imdbId
        $movieId     = $movie.id

        if (-not $currentPath) { $counts.NoPath++; continue }

        $folderName = Split-Path $currentPath -Leaf
        $parentDir  = Split-Path $currentPath -Parent

        if ($year -eq 0 -or -not $year) {
            Write-Log ("  [NO YEAR]    {0} -- skipped, no release year in Radarr" -f $title) 'Yellow'
            $noYearList.Add($title)
            $counts.NoYear++
            continue
        }

        if (-not (Test-Path -LiteralPath $currentPath)) {
            Write-Log ("  [MISSING]    {0} -- path not found: {1}" -f $title, $currentPath) 'Yellow'
            $counts.PathMissing++
            continue
        }

        $newFolderName = Get-RadarrTargetFolderName $title $year $imdbId $usePlex
        $newPath       = Join-Path $parentDir $newFolderName

        if ($folderName -eq $newFolderName) { $counts.AlreadyCorrect++; continue }

        # Soft match: if the only difference between the existing folder name
        # and the target is the presence of ' - ' separators (e.g. folder has
        # "13 Hours - The Secret Soldiers of Benghazi" but CleanTitle produces
        # "13 Hours The Secret Soldiers of Benghazi"), skip the rename.
        # This preserves existing well-formatted folders from earlier Radarr
        # conventions without forcing a mass cosmetic rename.
        # We still rename if the year differs, quality tags are present, or
        # the title itself is substantively different.
        $normFolder = ($folderName  -replace ' - ', ' ' -replace '\s+', ' ').Trim()
        $normTarget = ($newFolderName -replace ' - ', ' ' -replace '\s+', ' ').Trim()
        if ($normFolder -eq $normTarget) { $counts.AlreadyCorrect++; continue }

        if (-not $LiveRename) {
            Write-Log ("  [WOULD RENAME]") 'White'
            Write-Log ("      From : {0}" -f $currentPath) 'White'
            Write-Log ("      To   : {0}" -f $newPath) 'Cyan'
            $counts.Renamed++
        } else {
            if ((Test-Path -LiteralPath $newPath) -and ($newPath -ne $currentPath)) {
                Write-Log ("  [CONFLICT]   {0} -- target folder already exists." -f $title) 'Red'
                $failedList.Add(("{0} -- target folder already exists" -f $title))
                $counts.Failed++
                continue
            }
            try {
                Rename-Item -LiteralPath $currentPath -NewName $newFolderName -ErrorAction Stop
                $movie.path = $newPath
                $result = Invoke-RadarrPut "movie/$movieId" $movie
                if ($result) {
                    Write-Log ("  [RENAMED]") 'Green'
                    Write-Log ("      From : {0}" -f $currentPath) 'Green'
                    Write-Log ("      To   : {0}" -f $newPath) 'Green'
                    $counts.Renamed++
                } else {
                    Write-Log ("  [API FAIL]   {0} -- folder renamed but Radarr update failed. Rolling back." -f $title) 'Red'
                    try {
                        Rename-Item -LiteralPath $newPath -NewName $folderName -ErrorAction Stop
                        Write-Log ("               Rollback successful.") 'Yellow'
                    } catch {
                        Write-Log ("               Rollback FAILED. Folder is now at: {0}" -f $newPath) 'Red'
                        Write-Log ("               Manually update the path in Radarr for this movie.") 'Red'
                    }
                    $failedList.Add(("{0} -- Radarr API update failed" -f $title))
                    $counts.Failed++
                }
            } catch {
                Write-Log ("  [ERROR]      {0} -- {1}" -f $title, $_) 'Red'
                $failedList.Add(("{0} -- {1}" -f $title, $_))
                $counts.Failed++
            }
        }
    }

    Write-Log ''
    Write-SectionHeader 'SUMMARY'
    Write-Log ''

    if ($LiveRename) {
        Write-Log ("  Renamed          : {0}  movies" -f $counts.Renamed) 'Green'
        Write-Log ("  Failed           : {0}  movies" -f $counts.Failed) $(if ($counts.Failed) { 'Red' } else { 'Green' })
    } else {
        Write-Log ("  Would rename     : {0}  movies" -f $counts.Renamed) 'Cyan'
    }
    Write-Log ("  Already correct  : {0}  movies" -f $counts.AlreadyCorrect) 'White'
    Write-Log ("  No year in Radarr: {0}  movies (skipped)" -f $counts.NoYear) 'Yellow'
    Write-Log ("  Path missing     : {0}  movies (Radarr path not found on disk)" -f $counts.PathMissing) 'Yellow'

    if ($noYearList.Count) {
        Write-Log ''
        Write-Log '  Movies with no release year in Radarr (cannot rename):' 'Yellow'
        foreach ($m in $noYearList | Sort-Object) { Write-Log ("    - {0}" -f $m) 'Yellow' }
        Write-Tip 'To add a release year: open the movie in Radarr > Edit > and verify the correct entry is matched'
    }
    if ($failedList.Count) {
        Write-Log ''
        Write-Log '  Failed renames (require manual attention):' 'Red'
        foreach ($f in $failedList) { Write-Log ("    - {0}" -f $f) 'Red' }
    }

    Write-Log ''
    if (-not $LiveRename) {
        Write-Log '  Re-run and choose Live Rename to apply these changes.' 'Cyan'
    } else {
        Write-Log '  Done.' 'Green'
    }
    Write-Log ("  Log saved to: {0}" -f $Script:LogFile) 'Cyan'
}

# ================================================================
#  TOOL 4: LIDARR FOLDER RENAMER
# ================================================================
function Invoke-LidarrGet ([string]$Endpoint) {
    $uri = "$($LidarrConfig.BaseUrl.TrimEnd('/'))/api/v1/$Endpoint"
    try {
        return Invoke-RestMethod -Uri $uri `
            -Headers @{ 'X-Api-Key' = $LidarrConfig.ApiKey } `
            -Method Get -ErrorAction Stop
    }
    catch {
        Write-Log ("  [ERROR] GET {0} -- {1}" -f $uri, $_) 'Red'
        return $null
    }
}

function Invoke-LidarrPut ([string]$Endpoint, [object]$Body) {
    $uri = "$($LidarrConfig.BaseUrl.TrimEnd('/'))/api/v1/$Endpoint"
    try {
        $json  = $Body | ConvertTo-Json -Depth 20 -Compress
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($json)
        return Invoke-RestMethod -Uri $uri `
            -Headers @{ 'X-Api-Key' = $LidarrConfig.ApiKey; 'Content-Type' = 'application/json; charset=utf-8' } `
            -Method Put -Body $bytes -ErrorAction Stop
    }
    catch {
        Write-Log ("  [ERROR] PUT {0} -- {1}" -f $uri, $_) 'Red'
        return $null
    }
}

function Get-LidarrCleanArtistName ([string]$Name) {
    # Mirrors Lidarr's artist folder sanitization:
    # colons become space-dash, other illegal Windows filename
    # characters are removed entirely.
    $clean = $Name -replace ':', ' -'
    $clean = $clean -replace '[\\/<>"\|\?\*]', ''
    $clean = $clean -replace '\s+', ' '
    return $clean.Trim()
}

function Invoke-LidarrFolderRenamer {
    param([bool]$LiveRename = $false)

    Start-Log 'FolderBoy_LidarrRenamer'
    $modeLabel = if ($LiveRename) { 'Live Rename' } else { 'Dry Run' }

    Write-Log ''
    Write-Log '  ============================================================' 'Cyan'
    Write-Log ("   Lidarr Folder Renamer -- {0}" -f $modeLabel) 'Cyan'
    Write-Log ('   {0}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')) 'Cyan'
    Write-Log '  ============================================================' 'Cyan'

    if (-not $LiveRename) {
        Write-Log ''
        Write-Log '  DRY RUN MODE: No folders will be renamed. Lidarr will not be updated.' 'Cyan'
        Write-Log '  This run previews what WOULD be renamed.' 'Cyan'
        Write-Log '  Review the output, then re-run and choose Live Rename to apply.' 'Cyan'
    }

    Write-Log ''
    Write-Tip 'Lidarr Artist Folder Format should be: {Artist Name}'
    Write-Tip 'Set in Lidarr: Settings > Media Management > (show advanced) > Artist Folder Format'
    Write-Log ''

    if ($LiveRename) {
        if (-not (Confirm-LiveAction 'This will rename artist folders on disk and update Lidarr paths via API.')) { return }
    }

    Write-Log '  Fetching Lidarr library...' 'White'
    $allArtists = Invoke-LidarrGet 'artist'
    if (-not $allArtists) {
        Write-Log '  Could not reach Lidarr API. Check BaseUrl and ApiKey in FolderBoy.config.ps1.' 'Red'
        return
    }
    Write-Log ("  Found {0} artists in Lidarr." -f $allArtists.Count) 'White'
    Write-Log ''

    $counts = @{
        AlreadyCorrect = 0; NoPath = 0; PathMissing = 0
        Renamed        = 0; Failed = 0
    }
    $failedList = [System.Collections.Generic.List[string]]::new()

    Write-SectionHeader 'PROCESSING ARTISTS'
    Write-Log ''

    foreach ($artist in $allArtists | Sort-Object { $_.artistName }) {
        $currentPath = if ($artist.path) { $artist.path.TrimEnd('\').TrimEnd('/') } else { $null }
        $artistName  = $artist.artistName
        $artistId    = $artist.id

        if (-not $currentPath) { $counts.NoPath++; continue }

        $folderName = Split-Path $currentPath -Leaf
        $parentDir  = Split-Path $currentPath -Parent

        if (-not (Test-Path -LiteralPath $currentPath)) {
            Write-Log ("  [MISSING]    {0} -- path not found: {1}" -f $artistName, $currentPath) 'Yellow'
            $counts.PathMissing++
            continue
        }

        $newFolderName = Get-LidarrCleanArtistName $artistName
        $newPath       = Join-Path $parentDir $newFolderName

        if ($folderName -eq $newFolderName) { $counts.AlreadyCorrect++; continue }

        if (-not $LiveRename) {
            Write-Log ("  [WOULD RENAME]") 'White'
            Write-Log ("      From : {0}" -f $currentPath) 'White'
            Write-Log ("      To   : {0}" -f $newPath) 'Cyan'
            $counts.Renamed++
        } else {
            if ((Test-Path -LiteralPath $newPath) -and ($newPath -ne $currentPath)) {
                Write-Log ("  [CONFLICT]   {0} -- target folder already exists." -f $artistName) 'Red'
                $failedList.Add(("{0} -- target folder already exists" -f $artistName))
                $counts.Failed++
                continue
            }
            try {
                Rename-Item -LiteralPath $currentPath -NewName $newFolderName -ErrorAction Stop
                $artist.path = $newPath
                $result = Invoke-LidarrPut "artist/$artistId" $artist
                if ($result) {
                    Write-Log ("  [RENAMED]") 'Green'
                    Write-Log ("      From : {0}" -f $currentPath) 'Green'
                    Write-Log ("      To   : {0}" -f $newPath) 'Green'
                    $counts.Renamed++
                } else {
                    Write-Log ("  [API FAIL]   {0} -- folder renamed but Lidarr update failed. Rolling back." -f $artistName) 'Red'
                    try {
                        Rename-Item -LiteralPath $newPath -NewName $folderName -ErrorAction Stop
                        Write-Log ("               Rollback successful.") 'Yellow'
                    } catch {
                        Write-Log ("               Rollback FAILED. Folder is now at: {0}" -f $newPath) 'Red'
                        Write-Log ("               Manually update the path in Lidarr for this artist.") 'Red'
                    }
                    $failedList.Add(("{0} -- Lidarr API update failed" -f $artistName))
                    $counts.Failed++
                }
            } catch {
                Write-Log ("  [ERROR]      {0} -- {1}" -f $artistName, $_) 'Red'
                $failedList.Add(("{0} -- {1}" -f $artistName, $_))
                $counts.Failed++
            }
        }
    }

    Write-Log ''
    Write-SectionHeader 'SUMMARY'
    Write-Log ''

    if ($LiveRename) {
        Write-Log ("  Renamed          : {0}  artists" -f $counts.Renamed) 'Green'
        Write-Log ("  Failed           : {0}  artists" -f $counts.Failed) $(if ($counts.Failed) { 'Red' } else { 'Green' })
    } else {
        Write-Log ("  Would rename     : {0}  artists" -f $counts.Renamed) 'Cyan'
    }
    Write-Log ("  Already correct  : {0}  artists" -f $counts.AlreadyCorrect) 'White'
    Write-Log ("  Path missing     : {0}  artists (Lidarr path not found on disk)" -f $counts.PathMissing) 'Yellow'

    if ($failedList.Count) {
        Write-Log ''
        Write-Log '  Failed renames (require manual attention):' 'Red'
        foreach ($f in $failedList) { Write-Log ("    - {0}" -f $f) 'Red' }
    }

    Write-Log ''
    if (-not $LiveRename) {
        Write-Log '  Re-run and choose Live Rename to apply these changes.' 'Cyan'
    } else {
        Write-Log '  Done.' 'Green'
    }
    Write-Log ("  Log saved to: {0}" -f $Script:LogFile) 'Cyan'
}

# ================================================================
#  TOOL 5: ORPHAN SCANNER
# ================================================================
function Write-OrphanAppSummary ($AppName, $Stats) {
    Write-Log ''
    Write-Log ("  -- {0} Summary --" -f $AppName) 'Yellow'
    Write-Log ("    Not in {0,-8}: {1,4}  folders" -f $AppName, $Stats.NotInArr.Count) $(if ($Stats.NotInArr.Count) { 'Red' } else { 'Green' })
    Write-Log ("    Needs Review   : {0,4}  folders" -f $Stats.NeedsReview.Count) $(if ($Stats.NeedsReview.Count) { 'Yellow' } else { 'Green' })
    Write-Log ("    Matched OK     : {0,4}  folders" -f $Stats.Matched) 'Green'
}

function Invoke-RadarrScan {
    if (-not $RadarrConfig.Enabled) {
        Write-Log '  Radarr is disabled in config -- skipping.' 'DarkGray'
        return $null
    }

    Write-Log ("  Radarr: {0}" -f $RadarrConfig.BaseUrl) 'White'
    Write-Tip 'Radarr Movie Folder Format (minimum): {Movie CleanTitle} ({Release Year})'
    Write-Tip 'Guide: https://trash-guides.info/Radarr/Radarr-recommended-naming-scheme/'

    $movies = Invoke-ArrApi $RadarrConfig.BaseUrl $RadarrConfig.ApiKey 'movie'
    if (-not $movies) {
        Write-Log '  Could not reach Radarr API. Check BaseUrl and ApiKey in FolderBoy.config.ps1.' 'Red'
        return $null
    }

    $radarrPaths = @{}
    foreach ($m in $movies) {
        if ($m.path) { $radarrPaths[(Normalize-Path $m.path)] = $m.title }
    }
    Write-Log ("  Library: {0} movies  |  {1} with paths set" -f $movies.Count, $radarrPaths.Count) 'White'

    $stats = @{
        NotInArr    = [System.Collections.Generic.List[hashtable]]::new()
        NeedsReview = [System.Collections.Generic.List[hashtable]]::new()
        NameMatched = [System.Collections.Generic.List[hashtable]]::new()
        Matched     = 0
    }

    foreach ($rootPath in $RadarrConfig.Paths) {
        if (-not (Test-Path -LiteralPath $rootPath)) {
            Write-Log ("  [WARN] Path not found: {0}" -f $rootPath) 'Yellow'
            continue
        }
        $folders = Get-ChildItem -LiteralPath $rootPath -Directory -ErrorAction SilentlyContinue
        Write-Log ("  Scanning {0} ({1} folders)" -f $rootPath, $folders.Count) 'White'
        foreach ($folder in $folders) {
            if ($radarrPaths.ContainsKey((Normalize-Path $folder.FullName))) {
                $stats.Matched++
            } else {
                $sz = Get-FolderSize $folder.FullName
                $stats.NotInArr.Add(@{ Path = $folder.FullName; Size = $sz.Display; Bytes = $sz.Bytes; App = 'Radarr' })
            }
        }
    }

    if ($stats.NotInArr.Count) {
        Write-Log ''
        Write-Log '  [ NOT IN RADARR -- folder path not managed by Radarr ]' 'Red'
        Write-Log '  These folders exist on disk but Radarr has no record of them.' 'DarkGray'
        foreach ($item in $stats.NotInArr | Sort-Object { $_.Path }) {
            Write-Log ("    {0}  |  {1}" -f $item.Path.PadRight($PathPad), $item.Size.PadLeft(10)) 'Red'
        }
    }

    Write-OrphanAppSummary 'Radarr' $stats
    return $stats
}

function Invoke-SonarrScan {
    if (-not $SonarrConfig.Enabled) {
        Write-Log '  Sonarr is disabled in config -- skipping.' 'DarkGray'
        return $null
    }

    Write-Log ("  Sonarr: {0}" -f $SonarrConfig.BaseUrl) 'White'
    Write-Tip 'Sonarr Series Folder Format should be: {Series TitleYear} {imdb-{ImdbId}}'
    Write-Tip 'Run the Sonarr Folder Renamer (option 2) to add ID tags to existing folders.'

    $series = Invoke-ArrApi $SonarrConfig.BaseUrl $SonarrConfig.ApiKey 'series'
    if (-not $series) {
        Write-Log '  Could not reach Sonarr API. Check BaseUrl and ApiKey in FolderBoy.config.ps1.' 'Red'
        return $null
    }

    $imdbLookup  = @{}
    $tvdbLookup  = @{}
    $titleLookup = @{}
    foreach ($s in $series) {
        if ($s.imdbId) { $imdbLookup[$s.imdbId]      = $s.title }
        if ($s.tvdbId) { $tvdbLookup["$($s.tvdbId)"] = $s.title }
        $titleLookup[(Normalize $s.title)] = $s.title
        if ($s.originalTitle) { $titleLookup[(Normalize $s.originalTitle)] = $s.title }
    }
    Write-Log ("  Library: {0} series" -f $series.Count) 'White'

    $stats = @{
        NotInArr    = [System.Collections.Generic.List[hashtable]]::new()
        NeedsReview = [System.Collections.Generic.List[hashtable]]::new()
        NameMatched = [System.Collections.Generic.List[hashtable]]::new()
        Matched     = 0
    }

    foreach ($rootPath in $SonarrConfig.Paths) {
        if (-not (Test-Path -LiteralPath $rootPath)) {
            Write-Log ("  [WARN] Path not found: {0}" -f $rootPath) 'Yellow'
            continue
        }
        $folders = Get-ChildItem -LiteralPath $rootPath -Directory -ErrorAction SilentlyContinue
        Write-Log ("  Scanning {0} ({1} folders)" -f $rootPath, $folders.Count) 'White'

        foreach ($folder in $folders) {
            $imdbId = if ($folder.Name -match '\{imdb-(tt\d+)\}') { $Matches[1] } else { $null }
            $tvdbId = if ($folder.Name -match '\{tvdb-(\d+)\}')   { $Matches[1] } else { $null }

            if ($imdbId -or $tvdbId) {
                $hit = ($imdbId -and $imdbLookup.ContainsKey($imdbId)) -or
                       ($tvdbId -and $tvdbLookup.ContainsKey($tvdbId))
                if ($hit) {
                    $stats.Matched++
                } else {
                    $sz    = Get-FolderSize $folder.FullName
                    $idStr = (@($imdbId, $tvdbId) | Where-Object { $_ }) -join ' / '
                    $stats.NotInArr.Add(@{ Path = $folder.FullName; Size = $sz.Display; Bytes = $sz.Bytes; Id = $idStr; App = 'Sonarr' })
                }
            } else {
                $clean   = ($folder.Name -replace '\{[^}]+\}', '' -replace '\s+', ' ').Trim()
                $title   = if ($clean -match '^(.+?)\s*\(\d{4}\)') { $Matches[1].Trim() } else { $clean }
                $nameHit = $titleLookup.ContainsKey((Normalize $title))
                $sz      = Get-FolderSize $folder.FullName
                if ($nameHit) {
                    $stats.Matched++
                    $stats.NameMatched.Add(@{ Path = $folder.FullName; Size = $sz.Display; Bytes = $sz.Bytes; App = 'Sonarr' })
                } else {
                    $stats.NeedsReview.Add(@{ Path = $folder.FullName; Size = $sz.Display; Bytes = $sz.Bytes; App = 'Sonarr' })
                }
            }
        }
    }

    if ($stats.NotInArr.Count) {
        Write-Log ''
        Write-Log '  [ NOT IN SONARR -- ID tag present but not found in Sonarr library ]' 'Red'
        Write-Log '  High confidence orphans. ID tag exists but Sonarr has no matching series.' 'DarkGray'
        foreach ($item in $stats.NotInArr | Sort-Object { $_.Path }) {
            Write-Log ("    {0}  |  {1}  |  ID: {2}" -f $item.Path.PadRight($PathPad), $item.Size.PadLeft(10), $item.Id) 'Red'
        }
    }
    if ($stats.NeedsReview.Count) {
        Write-Log ''
        Write-Log '  [ NEEDS REVIEW -- no ID tag, no name match in Sonarr ]' 'Yellow'
        Write-Log '  No ID tag and name did not match any Sonarr series.' 'DarkGray'
        Write-Log '  May be unmanaged media or folders with slightly different names in Sonarr.' 'DarkGray'
        foreach ($item in $stats.NeedsReview | Sort-Object { $_.Path }) {
            Write-Log ("    {0}  |  {1}" -f $item.Path.PadRight($PathPad), $item.Size.PadLeft(10)) 'Yellow'
        }
    }
    if ($stats.NameMatched.Count) {
        Write-Log ''
        Write-Log '  [ NAME MATCHED (no ID tag) -- counted as matched ]' 'DarkGray'
        Write-Log '  Name matched a Sonarr series but no ID tag to confirm. Run the Sonarr Folder Renamer to add tags.' 'DarkGray'
        foreach ($item in $stats.NameMatched | Sort-Object { $_.Path }) {
            Write-Log ("    {0}  |  {1}" -f $item.Path.PadRight($PathPad), $item.Size.PadLeft(10)) 'DarkGray'
        }
    }

    Write-OrphanAppSummary 'Sonarr' $stats
    return $stats
}

function Invoke-LidarrScan {
    if (-not $LidarrConfig.Enabled) {
        Write-Log '  Lidarr is disabled in config -- skipping.' 'DarkGray'
        return $null
    }

    Write-Log ("  Lidarr: {0}" -f $LidarrConfig.BaseUrl) 'White'
    Write-Tip 'Lidarr Artist Folder Format should be: {Artist Name}'
    Write-Tip 'Lidarr Album Folder Format should be: {Album Title} {(Album Disambiguation)}'
    Write-Tip 'Guide: https://wiki.servarr.com/lidarr/naming-guide'

    $artists = Invoke-ArrApi $LidarrConfig.BaseUrl $LidarrConfig.ApiKey 'artist' 'v1'
    if (-not $artists) {
        Write-Log '  Could not reach Lidarr API. Check BaseUrl and ApiKey in FolderBoy.config.ps1.' 'Red'
        return $null
    }

    $artistLookup = @{}
    foreach ($a in $artists) { $artistLookup[(Normalize $a.artistName)] = $a.artistName }
    Write-Log ("  Library: {0} artists" -f $artists.Count) 'White'

    $stats = @{
        NotInArr    = [System.Collections.Generic.List[hashtable]]::new()
        NeedsReview = [System.Collections.Generic.List[hashtable]]::new()
        NameMatched = [System.Collections.Generic.List[hashtable]]::new()
        Matched     = 0
    }

    foreach ($rootPath in $LidarrConfig.Paths) {
        if (-not (Test-Path -LiteralPath $rootPath)) {
            Write-Log ("  [WARN] Path not found: {0}" -f $rootPath) 'Yellow'
            continue
        }
        $folders = Get-ChildItem -LiteralPath $rootPath -Directory -ErrorAction SilentlyContinue
        Write-Log ("  Scanning {0} ({1} artist folders)" -f $rootPath, $folders.Count) 'White'

        foreach ($folder in $folders) {
            $normName = Normalize $folder.Name
            if ($artistLookup.ContainsKey($normName)) {
                $stats.Matched++
            } else {
                $stripped = $normName -replace '[^a-z0-9]', ''
                $fuzzyHit = $artistLookup.Keys |
                    Where-Object { ($_ -replace '[^a-z0-9]', '') -eq $stripped } |
                    Select-Object -First 1
                $sz = Get-FolderSize $folder.FullName
                if ($fuzzyHit) {
                    $stats.NeedsReview.Add(@{
                        Path       = $folder.FullName
                        Size       = $sz.Display
                        Bytes      = $sz.Bytes
                        FuzzyMatch = $artistLookup[$fuzzyHit]
                        App        = 'Lidarr'
                    })
                } else {
                    $stats.NotInArr.Add(@{ Path = $folder.FullName; Size = $sz.Display; Bytes = $sz.Bytes; App = 'Lidarr' })
                }
            }
        }
    }

    if ($stats.NotInArr.Count) {
        Write-Log ''
        Write-Log '  [ NOT IN LIDARR -- artist folder not managed by Lidarr ]' 'Red'
        foreach ($item in $stats.NotInArr | Sort-Object { $_.Path }) {
            Write-Log ("    {0}  |  {1}" -f $item.Path.PadRight($PathPad), $item.Size.PadLeft(10)) 'Red'
        }
    }
    if ($stats.NeedsReview.Count) {
        Write-Log ''
        Write-Log '  [ NEEDS REVIEW -- fuzzy name match only, verify before deleting ]' 'Yellow'
        Write-Log '  Closely resembles a Lidarr artist name but did not match exactly.' 'DarkGray'
        Write-Log '  Parenthetical suffixes in folder names are a common cause.' 'DarkGray'
        foreach ($item in $stats.NeedsReview | Sort-Object { $_.Path }) {
            Write-Log ("    {0}  |  {1}  |  Possible match: {2}" -f $item.Path.PadRight($PathPad), $item.Size.PadLeft(10), $item.FuzzyMatch) 'Yellow'
        }
    }

    Write-OrphanAppSummary 'Lidarr' $stats
    return $stats
}

function Invoke-OrphanInteractiveDelete ($RadarrStats, $SonarrStats, $LidarrStats) {
    $notInArr    = [System.Collections.Generic.List[hashtable]]::new()
    $needsReview = [System.Collections.Generic.List[hashtable]]::new()
    $nameMatched = [System.Collections.Generic.List[hashtable]]::new()

    foreach ($stats in @($RadarrStats, $SonarrStats, $LidarrStats)) {
        if (-not $stats) { continue }
        foreach ($item in $stats.NotInArr)    { $notInArr.Add($item) }
        foreach ($item in $stats.NeedsReview) { $needsReview.Add($item) }
        if ($stats.NameMatched) { foreach ($item in $stats.NameMatched) { $nameMatched.Add($item) } }
    }

    $totalAll = $notInArr.Count + $needsReview.Count + $nameMatched.Count
    if ($totalAll -eq 0) {
        Write-Log ''
        Write-Log '  No orphaned items found. Nothing to delete.' 'Green'
        return
    }

    Write-Log ''
    Write-Log '  ============================================================' 'Cyan'
    Write-Log '   SELECT ITEMS TO REVIEW FOR DELETION' 'Cyan'
    Write-Log '  ============================================================' 'Cyan'
    Write-Log ''
    Write-Log '  Confidence levels:' 'DarkGray'
    Write-Log '    NOT IN ARR   -- High.   ID tag present but not found in *arr library.' 'DarkGray'
    Write-Log '    NEEDS REVIEW -- Medium. No ID tag and no name match found in *arr.' 'DarkGray'
    Write-Log '    NAME MATCHED -- Low.    Name matched but no ID tag to confirm.' 'DarkGray'
    Write-Log ''
    Write-Log ("  (1) NOT IN ARR only             ({0,4} items -- high confidence)" -f $notInArr.Count) 'White'
    Write-Log ("  (2) NOT IN ARR + NEEDS REVIEW   ({0,4} items)" -f ($notInArr.Count + $needsReview.Count)) 'White'
    Write-Log ("  (3) ALL flagged items            ({0,4} items -- includes low-confidence)" -f $totalAll) 'White'
    Write-Log ("  (4) Exit without deleting") 'White'
    Write-Log ''

    do { $catChoice = Read-Host '  Choice' } until ($catChoice -in '1','2','3','4')
    if ($catChoice -eq '4') { Write-Log '  Exited. No changes made.' 'Yellow'; return }

    $candidates = [System.Collections.Generic.List[hashtable]]::new()
    foreach ($item in $notInArr) { $candidates.Add($item) }
    if ($catChoice -in '2','3') { foreach ($item in $needsReview) { $candidates.Add($item) } }
    if ($catChoice -eq '3')     { foreach ($item in $nameMatched) { $candidates.Add($item) } }
    $candidates = $candidates | Sort-Object { $_.Path }

    Write-Log ''
    Write-Log '  ============================================================' 'Cyan'
    Write-Log ("   REVIEWING {0} ITEMS" -f $candidates.Count) 'Cyan'
    Write-Log '   (D)elete  (S)kip  (Q)uit review' 'Cyan'
    Write-Log '  ============================================================' 'Cyan'
    Write-Log ''
    Write-Log '  Items marked D are queued -- nothing is deleted until you confirm at the end.' 'DarkGray'

    $deleteQueue = [System.Collections.Generic.List[hashtable]]::new()
    $skipped     = 0
    $quitEarly   = $false

    foreach ($item in $candidates) {
        Write-Log ''
        Write-Log ("  Path : {0}" -f $item.Path) 'White'
        Write-Log ("  Size : {0}  |  App: {1}" -f $item.Size, $item.App) 'White'
        if ($item.Id)         { Write-Log ("  ID   : {0}" -f $item.Id) 'DarkGray' }
        if ($item.FuzzyMatch) { Write-Log ("  Note : Possible {0} match -- {1}" -f $item.App, $item.FuzzyMatch) 'Yellow' }

        do { $choice = (Read-Host '  (D)elete / (S)kip / (Q)uit').ToUpper().Trim() } until ($choice -in 'D','S','Q')

        switch ($choice) {
            'D' { $deleteQueue.Add($item); Write-Log '  --> Queued for deletion' 'Red' }
            'S' { $skipped++; Write-Log '  --> Skipped' 'DarkGray' }
            'Q' { $quitEarly = $true; Write-Log '  --> Review stopped by user' 'Yellow' }
        }
        if ($quitEarly) { break }
    }

    if ($deleteQueue.Count -eq 0) {
        Write-Log ''
        Write-Log '  No items queued for deletion.' 'Yellow'
        return
    }

    $totalBytes = ($deleteQueue | Measure-Object -Property Bytes -Sum).Sum
    $totalGB    = [math]::Round($totalBytes / 1GB, 2)
    $totalMB    = [math]::Round($totalBytes / 1MB, 1)

    Write-Log ''
    Write-Log '  ============================================================' 'Cyan'
    Write-Log '   DELETION QUEUE' 'Cyan'
    Write-Log '  ============================================================' 'Cyan'
    Write-Log ("  Items queued : {0}" -f $deleteQueue.Count) 'Red'
    Write-Log ("  Items skipped: {0}" -f $skipped) 'DarkGray'
    Write-Log ("  Total size   : {0} GB  ({1} MB)" -f $totalGB, $totalMB) 'Red'
    Write-Log ''
    foreach ($item in $deleteQueue) {
        Write-Log ("    {0}  |  {1}" -f $item.Path.PadRight($PathPad), $item.Size.PadLeft(10)) 'Red'
    }

    if (-not (Confirm-LiveAction 'The folders listed above will be permanently deleted.')) { return }

    Write-Log ''
    Write-SectionHeader 'DELETING'

    $deleted = 0; $failed = 0; $deletedBytes = [long]0

    foreach ($item in $deleteQueue) {
        if (-not (Test-Path -LiteralPath $item.Path)) {
            Write-Log ("  [SKIP]    {0} -- no longer exists on disk" -f $item.Path) 'Yellow'
            continue
        }
        try {
            Remove-Item -LiteralPath $item.Path -Recurse -Force -ErrorAction Stop
            Write-Log ("  [DELETED] {0}  ({1})" -f $item.Path.PadRight($PathPad), $item.Size) 'Green'
            $deleted++
            $deletedBytes += $item.Bytes
        } catch {
            Write-Log ("  [FAILED]  {0}" -f $item.Path) 'Red'
            Write-Log ("            {0}" -f $_) 'Red'
            $failed++
        }
    }

    $deletedGB = [math]::Round($deletedBytes / 1GB, 2)
    $deletedMB = [math]::Round($deletedBytes / 1MB, 1)

    Write-Log ''
    Write-Log ("  Deleted : {0}  folders  |  {1} GB  ({2} MB) reclaimed" -f $deleted, $deletedGB, $deletedMB) 'Green'
    Write-Log ("  Failed  : {0}  folders" -f $failed) $(if ($failed) { 'Red' } else { 'Green' })
}

function Invoke-OrphanScanner {
    param([bool]$WithDelete = $false)

    Start-Log 'FolderBoy_Scanner'

    Write-Log ''
    Write-Log '  ============================================================' 'Cyan'
    $scanModeLabel = if ($WithDelete) { 'Scan + Delete' } else { 'Scan Only' }
    Write-Log ("   Orphan Scanner -- {0}" -f $scanModeLabel) 'Cyan'
    Write-Log ('   {0}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')) 'Cyan'
    Write-Log '  ============================================================' 'Cyan'

    if (-not $WithDelete) {
        Write-Log ''
        Write-Log '  SCAN ONLY MODE: No files will be deleted.' 'Cyan'
        Write-Log '  This run reports orphaned folders only.' 'Cyan'
        Write-Log '  Re-run and choose Scan + Delete to act on the results.' 'Cyan'
    }

    Write-Log ''
    Write-Log '  Scanning libraries...' 'White'

    Write-SectionHeader 'RADARR'
    $radarrStats = Invoke-RadarrScan

    Write-SectionHeader 'SONARR'
    $sonarrStats = Invoke-SonarrScan

    Write-SectionHeader 'LIDARR'
    $lidarrStats = Invoke-LidarrScan

    Write-Log ''
    Write-Log '  ============================================================' 'Cyan'
    Write-Log '   OVERALL SUMMARY' 'Cyan'
    Write-Log '  ============================================================' 'Cyan'

    $grandNotInArr = 0; $grandNeedsReview = 0; $grandMatched = 0

    foreach ($pair in @(
        @{ Name = 'Radarr'; Stats = $radarrStats; Cfg = $RadarrConfig },
        @{ Name = 'Sonarr'; Stats = $sonarrStats; Cfg = $SonarrConfig },
        @{ Name = 'Lidarr'; Stats = $lidarrStats; Cfg = $LidarrConfig }
    )) {
        if (-not $pair.Cfg.Enabled) {
            Write-Log ("  {0,-10}  Disabled" -f $pair.Name) 'DarkGray'
        } elseif ($pair.Stats) {
            $grandNotInArr    += $pair.Stats.NotInArr.Count
            $grandNeedsReview += $pair.Stats.NeedsReview.Count
            $grandMatched     += $pair.Stats.Matched
            Write-Log ("  {0,-10}  Not in arr: {1,4}   Needs review: {2,4}   Matched: {3,4}" -f `
                $pair.Name, $pair.Stats.NotInArr.Count, $pair.Stats.NeedsReview.Count, $pair.Stats.Matched) 'White'
        } else {
            Write-Log ("  {0,-10}  SKIPPED (API unreachable)" -f $pair.Name) 'Red'
        }
    }

    Write-Log ''
    Write-Log ("  Total NOT IN ARR   : {0}" -f $grandNotInArr)    $(if ($grandNotInArr)    { 'Red'    } else { 'Green' })
    Write-Log ("  Total NEEDS REVIEW : {0}" -f $grandNeedsReview) $(if ($grandNeedsReview) { 'Yellow' } else { 'Green' })
    Write-Log ("  Total MATCHED OK   : {0}" -f $grandMatched)     'Green'
    Write-Log ''
    Write-Log ("  Log saved to: {0}" -f $Script:LogFile) 'Cyan'

    if ($WithDelete) {
        Invoke-OrphanInteractiveDelete $radarrStats $sonarrStats $lidarrStats
    }
}

# ================================================================
#  MAIN MENU
# ================================================================
function Show-MainMenu {
    param($SessionLog)
    Write-Host ''
    Write-Host '  ============================================================' -ForegroundColor Cyan
    Write-Host '   FolderBoy  |  Media Library Manager' -ForegroundColor Cyan
    Write-Host '  ============================================================' -ForegroundColor Cyan
    Write-Host ''
    Write-Host '  (1) FolderBoy Cleaner    -- remove folders with no media files'
    Write-Host '  (2) Sonarr Folder Renamer -- rename series folders to standard format'
    Write-Host '  (3) Radarr Folder Renamer -- rename movie folders to standard format'
    Write-Host '  (4) Lidarr Folder Renamer -- rename artist folders to standard format'
    Write-Host '  (5) Orphan Scanner       -- find media not managed by any *arr app'
    Write-Host '  (6) Full Run             -- all Renamers then Scanner (recommended workflow)'
    Write-Host '  (7) Exit'
    Write-Host ''

    # Session activity log
    if ($SessionLog.Count -gt 0) {
        Write-Host '  This session:' -ForegroundColor DarkGray
        foreach ($entry in $SessionLog) {
            Write-Host ("    {0}" -f $entry) -ForegroundColor DarkGray
        }
        Write-Host ''
    }
}

function Select-SubMode ([string]$Prompt, [string[]]$Options) {
    Write-Host ''
    Write-Host ("  {0}" -f $Prompt) -ForegroundColor Cyan
    Write-Host ''
    for ($i = 0; $i -lt $Options.Count; $i++) {
        Write-Host ("    ({0}) {1}" -f ($i + 1), $Options[$i])
    }
    Write-Host ''
    do {
        $c = Read-Host '  Choice'
        $idx = 0
        $valid = [int]::TryParse($c, [ref]$idx) -and $idx -ge 1 -and $idx -le $Options.Count
    } until ($valid)
    return $idx
}

# ================================================================
#  ENTRY POINT
# ================================================================
$SessionLog = [System.Collections.Generic.List[string]]::new()

function Add-SessionEntry ([string]$Entry) {
    $time = Get-Date -Format 'HH:mm'
    $Script:SessionLog.Add(("[{0}] {1}" -f $time, $Entry))
}

do {
    Show-MainMenu $SessionLog
    do { $menuChoice = Read-Host '  Choice' } until ($menuChoice -in '1','2','3','4','5','6','7')

    switch ($menuChoice) {

        '1' {
            $mode = Select-SubMode 'FolderBoy Cleaner mode:' @(
                'Dry Run     -- preview which folders would be deleted (safe, no changes)'
                'Live Delete -- permanently delete folders with no media files'
            )
            $modeStr = if ($mode -eq 2) { 'Live Delete' } else { 'Dry Run' }
            $cleanerResult = Invoke-FolderBoyCleaner -LiveDelete ($mode -eq 2)
            $pathSummary = if ($cleanerResult.Paths.Count -eq 1) {
                $cleanerResult.Paths[0]
            } else {
                "{0} paths" -f $cleanerResult.Paths.Count
            }
            Add-SessionEntry ("FolderBoy Cleaner [{0}] {1} -- {2} -- complete" -f $modeStr, $cleanerResult.Label, $pathSummary)
        }

        '2' {
            if (-not $SonarrConfig.Enabled) {
                Write-Host ''
                Write-Host '  Sonarr is disabled in FolderBoy.config.ps1.' -ForegroundColor Yellow
                Write-Host '  Set Enabled = $true in $SonarrConfig to use this tool.' -ForegroundColor Yellow
            } else {
                $mode = Select-SubMode 'Sonarr Folder Renamer mode:' @(
                    'Dry Run     -- preview which folders would be renamed (safe, no changes)'
                    'Live Rename -- rename folders on disk and update Sonarr paths via API'
                )
                $modeStr = if ($mode -eq 2) { 'Live Rename' } else { 'Dry Run' }
                Invoke-SonarrRenamer -LiveRename ($mode -eq 2)
                Add-SessionEntry ("Sonarr Folder Renamer [{0}] -- complete" -f $modeStr)
            }
        }

        '3' {
            if (-not $RadarrConfig.Enabled) {
                Write-Host ''
                Write-Host '  Radarr is disabled in FolderBoy.config.ps1.' -ForegroundColor Yellow
                Write-Host '  Set Enabled = $true in $RadarrConfig to use this tool.' -ForegroundColor Yellow
            } else {
                $mode = Select-SubMode 'Radarr Folder Renamer mode:' @(
                    'Dry Run     -- preview which folders would be renamed (safe, no changes)'
                    'Live Rename -- rename folders on disk and update Radarr paths via API'
                )
                $modeStr = if ($mode -eq 2) { 'Live Rename' } else { 'Dry Run' }
                Invoke-RadarrFolderRenamer -LiveRename ($mode -eq 2)
                Add-SessionEntry ("Radarr Folder Renamer [{0}] -- complete" -f $modeStr)
            }
        }

        '4' {
            if (-not $LidarrConfig.Enabled) {
                Write-Host ''
                Write-Host '  Lidarr is disabled in FolderBoy.config.ps1.' -ForegroundColor Yellow
                Write-Host '  Set Enabled = $true in $LidarrConfig to use this tool.' -ForegroundColor Yellow
            } else {
                $mode = Select-SubMode 'Lidarr Folder Renamer mode:' @(
                    'Dry Run     -- preview which folders would be renamed (safe, no changes)'
                    'Live Rename -- rename folders on disk and update Lidarr paths via API'
                )
                $modeStr = if ($mode -eq 2) { 'Live Rename' } else { 'Dry Run' }
                Invoke-LidarrFolderRenamer -LiveRename ($mode -eq 2)
                Add-SessionEntry ("Lidarr Folder Renamer [{0}] -- complete" -f $modeStr)
            }
        }

        '5' {
            $mode = Select-SubMode 'Orphan Scanner mode:' @(
                'Scan Only     -- report orphaned folders (safe, no changes)'
                'Scan + Delete -- report then interactively select folders to delete'
            )
            $modeStr = if ($mode -eq 2) { 'Scan + Delete' } else { 'Scan Only' }
            Invoke-OrphanScanner -WithDelete ($mode -eq 2)
            Add-SessionEntry ("Orphan Scanner [{0}] -- complete" -f $modeStr)
        }

        '6' {
            Write-Host ''
            Write-Host '  Full Run: all Folder Renamers then Orphan Scanner.' -ForegroundColor Cyan
            Write-Host '  Running the renamers first maximizes ID tag coverage,' -ForegroundColor DarkGray
            Write-Host '  giving the scanner higher-confidence matches.' -ForegroundColor DarkGray

            if ($SonarrConfig.Enabled) {
                $sonarrMode = Select-SubMode 'Sonarr Folder Renamer mode:' @(
                    'Dry Run     -- preview renames only (safe, no changes)'
                    'Live Rename -- rename folders and update Sonarr'
                )
                $sonarrModeStr = if ($sonarrMode -eq 2) { 'Live Rename' } else { 'Dry Run' }
                Invoke-SonarrRenamer -LiveRename ($sonarrMode -eq 2)
                Add-SessionEntry ("Sonarr Folder Renamer [{0}] -- complete" -f $sonarrModeStr)
            } else {
                Write-Host '  Sonarr is disabled in config -- skipping.' -ForegroundColor DarkGray
            }

            if ($RadarrConfig.Enabled) {
                $radarrMode = Select-SubMode 'Radarr Folder Renamer mode:' @(
                    'Dry Run     -- preview renames only (safe, no changes)'
                    'Live Rename -- rename folders and update Radarr'
                )
                $radarrModeStr = if ($radarrMode -eq 2) { 'Live Rename' } else { 'Dry Run' }
                Invoke-RadarrFolderRenamer -LiveRename ($radarrMode -eq 2)
                Add-SessionEntry ("Radarr Folder Renamer [{0}] -- complete" -f $radarrModeStr)
            } else {
                Write-Host '  Radarr is disabled in config -- skipping.' -ForegroundColor DarkGray
            }

            if ($LidarrConfig.Enabled) {
                $lidarrMode = Select-SubMode 'Lidarr Folder Renamer mode:' @(
                    'Dry Run     -- preview renames only (safe, no changes)'
                    'Live Rename -- rename folders and update Lidarr'
                )
                $lidarrModeStr = if ($lidarrMode -eq 2) { 'Live Rename' } else { 'Dry Run' }
                Invoke-LidarrFolderRenamer -LiveRename ($lidarrMode -eq 2)
                Add-SessionEntry ("Lidarr Folder Renamer [{0}] -- complete" -f $lidarrModeStr)
            } else {
                Write-Host '  Lidarr is disabled in config -- skipping.' -ForegroundColor DarkGray
            }

            $scanMode = Select-SubMode 'Orphan Scanner mode:' @(
                'Scan Only     -- report orphans only (safe, no changes)'
                'Scan + Delete -- report then interactively select folders to delete'
            )
            $scanModeStr = if ($scanMode -eq 2) { 'Scan + Delete' } else { 'Scan Only' }
            Invoke-OrphanScanner -WithDelete ($scanMode -eq 2)
            Add-SessionEntry ("Orphan Scanner [{0}] -- complete" -f $scanModeStr)
        }

        '7' {
            Write-Host ''
            Write-Host '  Goodbye.' -ForegroundColor Cyan
            Write-Host ''
        }
    }

    if ($menuChoice -ne '7') {
        Write-Host ''
        Write-Host '  Press any key to return to the main menu...' -ForegroundColor DarkGray
        $null = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown')
    }

} while ($menuChoice -ne '7')